feat(client): qna page 개발
sickgyun/sickgyun-client pull request #126
Opened 2024-01-02 02:25 UTC by lsj0202

## ⛳️작업 내용

- qna page 퍼블리싱

## 📸스크린샷

## 📎레퍼런스

2024-01-02 10:17 UTC, SEOKKAMONI requested changes
수고하셨습니다~

2024-01-02 10:17 UTC, SEOKKAMONI commented on apps/client/src/app/career-qna/page.tsx
> +  };
`handleNextCarrerQna`와 같은 방식으로 변경해주세요 컨벤션입니당

2024-01-02 10:17 UTC, SEOKKAMONI commented on apps/client/src/components/qna-posting/QnaAskBox/index.tsx
> +  };
모든 것을 추상화하면 오히려 헷갈릴수있어요 다음과 같은 코드는 함수명을 명시적으로 변경하던가 아니면 onClick={() =>  setActiveCategory(index)} 이 더 나을수도있을것같아용

2024-01-02 10:17 UTC, SEOKKAMONI commented on apps/client/src/components/qna-posting/QnaAskBox/index.tsx
> +      <Stack flex-direction="virtical" spacing={0}>
spacing을 주지 않을때에는 flex를 사용합시다!

2024-01-02 10:17 UTC, SEOKKAMONI commented on apps/client/src/components/qna-posting/QnaAskBox/index.tsx
> +              <Text styleType="body1">{category.titleImage}</Text>
titleImage보단 thumbnail이 더 좋을것같아용

2024-01-02 10:17 UTC, SEOKKAMONI commented on apps/client/src/components/qna-posting/QnaCategory/index.tsx
> +  question_type: string;
카멜케이스를 사용합니다! 나중에 조정해봐요 우선은 카멜케이스가 컨벤션입니당

2024-01-02 10:17 UTC, SEOKKAMONI commented on apps/client/src/components/qna-posting/QnaCategory/index.tsx
> +  const question_type_emoji =
마찬가지입니다

2024-01-02 10:17 UTC, SEOKKAMONI commented on apps/client/src/components/qna-posting/QnaListBox/index.tsx
> +  const handleClick = (id: number) => {
무엇을 클릭한다는건지 모르겠어요 좀 더 명시적으로 추상화 해주세용

2024-01-02 10:17 UTC, SEOKKAMONI commented on apps/client/src/components/qna-posting/QnaPostingCard/index.tsx
> +  question_type: string;
마찬가지입니다

2024-01-02 10:17 UTC, SEOKKAMONI commented on apps/client/src/components/qna-posting/QnaPostingCard/index.tsx
> +  comment_count: number;
요가두용

2024-01-02 10:17 UTC, SEOKKAMONI commented on apps/client/src/components/qna-posting/QnaPostingCard/index.tsx
> +      <Stack direction="vertical" spacing={0}>
flex 사용!

2024-01-02 10:17 UTC, SEOKKAMONI commented on apps/client/src/components/qna-posting/QnaPostingList/index.tsx
> +      <StyledQnaPostingList currentQna={currentQna}>
currentQnaPage가 더 명시적이지 않을까요? currentQna를 하면 잘 모르겠어용

2024-01-02 12:05 UTC, lsj0202 commented on apps/client/src/app/career-qna/page.tsx
> +  };
아 그렇군요. 변경하겠습니다.

2024-01-02 12:27 UTC, lsj0202 commented on apps/client/src/components/qna-posting/QnaAskBox/index.tsx
> +  };
무지성으로 함수를 추상화하였는데 생각해보니 헷갈릴 수 있는 코드 같네요! 함수를 변경하도록 하겠습니다.

2024-01-02 12:27 UTC, lsj0202 commented on apps/client/src/components/qna-posting/QnaAskBox/index.tsx
> +      <Stack flex-direction="virtical" spacing={0}>
넵!

2024-01-02 12:31 UTC, lsj0202 commented on apps/client/src/components/qna-posting/QnaAskBox/index.tsx
> +              <Text styleType="body1">{category.titleImage}</Text>
넵

2024-01-02 12:32 UTC, lsj0202 commented on apps/client/src/components/qna-posting/QnaCategory/index.tsx
> +  question_type: string;
넵! 알겠습니다

2024-01-02 12:35 UTC, lsj0202 commented on apps/client/src/components/qna-posting/QnaListBox/index.tsx
> +  const handleClick = (id: number) => {
Title을 클릭한다는 것이엿는데 저만 알아보게 코드를 짰었군요.. 고치겠습니다.

2024-01-02 12:35 UTC, lsj0202 commented on apps/client/src/components/qna-posting/QnaPostingCard/index.tsx
> +  question_type: string;
넵

2024-01-02 12:36 UTC, lsj0202 commented on apps/client/src/components/qna-posting/QnaPostingCard/index.tsx
> +  comment_count: number;
옙

2024-01-02 12:44 UTC, lsj0202 commented on apps/client/src/components/qna-posting/QnaAskBox/index.tsx
> +  };
무지성으로 추상화 하는게 습관이 돼서 저도 모르게 사용한것 같습니다. 명시적인 함수로 변경 하도록 하겠습니다.

2024-01-02 12:45 UTC, lsj0202 commented on apps/client/src/components/qna-posting/QnaAskBox/index.tsx
> +              <Text styleType="body1">{category.titleImage}</Text>
그렇군요. 바꾸겠습니다.

2024-01-02 12:46 UTC, lsj0202 commented on apps/client/src/components/qna-posting/QnaPostingCard/index.tsx
> +      <Stack direction="vertical" spacing={0}>
넵

2024-01-02 12:46 UTC, lsj0202 commented on apps/client/src/components/qna-posting/QnaPostingList/index.tsx
> +      <StyledQnaPostingList currentQna={currentQna}>
그렇네요! 바꿧습니다.

2024-01-02 15:17 UTC, SEOKKAMONI requested changes
네이밍 전체적으로 한번만 더 생각해주시면 좋을것같아요!! 수고하셨어요!

2024-01-02 15:17 UTC, SEOKKAMONI commented on apps/client/src/app/career-qna/page.tsx
> +import { QNA_LIST } from '@/constants/qna-list';
```suggestion
import { QNA_LIST } from '@/constants/qna';
```

constants 파일명 qna-list 말고 qna라는 도메인 이름으로 묶어서 넣는것이 확장성을 고려하였을때 더 좋은 방법 같아용

2024-01-02 15:17 UTC, SEOKKAMONI commented on apps/client/src/app/career-qna/page.tsx
> +  };
```suggestion
  const handlePrevCareerQna = () => {
    if(currentQnaPage > 0) {
        setCurrentQnaPage((prev) => prev - 1);
    }
  };
```

이런식으로 짜는 것이 가독성이 더 좋을것같아용

2024-01-02 15:17 UTC, SEOKKAMONI commented on apps/client/src/components/qna-posting/QnaAskBox/index.tsx
> +const StyledAskCategory = styled.div<StyledAskCategoryProps>`
```suggestion
const StyledAskCategory = styled.div<{isActive: boolean}>`
```

이렇게 하는게 더 좋을것같아용 그리구 boolean 앞에는 is, has를 붙히도록합니당

2024-01-02 15:17 UTC, SEOKKAMONI commented on apps/client/src/components/qna-posting/QnaCategory/index.tsx
> +  const question_type_emoji =
```suggestion
  const questionTypeEmoji =
```

2024-01-02 15:17 UTC, SEOKKAMONI commented on apps/client/src/app/career-qna/page.tsx
> +const StyledCareerQnaAsk = styled.div`
```suggestion
const StyledCareerQna = styled.div`
```

Ask는 뺴도 될듯합니다! qna 안에 의미가 같이 섞여있다고 생각해용

2024-01-02 15:17 UTC, SEOKKAMONI commented on apps/client/src/app/career-qna/page.tsx
> +  const handleNextCarrerQna = () => {
```suggestion
  const handleNextPopularQna = () => {
```

요론식으로 하는게 좀 더 명시적일것같아요 참고해서 명시적인 네이밍을 생각해주세용

2024-01-02 15:17 UTC, SEOKKAMONI commented on apps/client/src/components/qna-posting/QnaCategory/index.tsx
> +  width: auto;
auto가 왜 필요한가요? (질문입니다)

2024-01-02 15:17 UTC, SEOKKAMONI commented on apps/client/src/components/qna-posting/QnaListBox/index.tsx
> +  overflow: hidden;
목적을 나타내는 네이밍으로 변경하면 좋을것같아요 지금은 기능을 나타내는 네이밍 같아요!

2024-01-02 15:17 UTC, SEOKKAMONI commented on apps/client/src/components/qna-posting/QnaPostingCard/index.tsx
> +  flex: 0 0 auto;
?? 이건 무슨 역할을 하나요?

2024-01-02 15:17 UTC, SEOKKAMONI commented on apps/client/src/components/qna-posting/QnaPostingCard/index.tsx
> +`;
마찬가지입니다!

2024-01-02 15:17 UTC, SEOKKAMONI commented on apps/client/src/components/qna-posting/QnaPostingList/index.tsx
> +const QnaPostingList = ({ currentQnaPage }) => {
Posting 보다는 Post가 맞지 않을까요??

2024-01-02 15:21 UTC, lsj0202 commented on apps/client/src/app/career-qna/page.tsx
> +import { QNA_LIST } from '@/constants/qna-list';
넵

2024-01-02 15:23 UTC, lsj0202 commented on apps/client/src/components/qna-posting/QnaAskBox/index.tsx
> +const StyledAskCategory = styled.div<StyledAskCategoryProps>`
넵!

2024-01-02 15:25 UTC, lsj0202 commented on apps/client/src/components/qna-posting/QnaCategory/index.tsx
> +  const question_type_emoji =
넵 컨벤션 지키겟슴니다

2024-01-02 15:26 UTC, lsj0202 commented on apps/client/src/app/career-qna/page.tsx
> +const StyledCareerQnaAsk = styled.div`
넵

2024-01-02 15:32 UTC, lsj0202 commented on apps/client/src/components/qna-posting/QnaCategory/index.tsx
> +  width: auto;
처음에 카테고리가 취업, 커리어, 기술 스택 인줄알고 글자 개수가 늘어날 때마다 유동적으로 크기를 변화시키고 싶어서 사용했습니다. 그런데 지금 카테고리는 전부 두 글자여서 사용하지 않아도 될듯합니다.

2024-01-02 15:34 UTC, lsj0202 commented on apps/client/src/components/qna-posting/QnaListBox/index.tsx
> +  overflow: hidden;
바꾸겠습니다!

2024-01-02 15:39 UTC, lsj0202 commented on apps/client/src/components/qna-posting/QnaPostingCard/index.tsx
> +  flex: 0 0 auto;
이게 캐러셀처럼 생긴 인기 qna 리스트의 넓이를 지정한 것인데요 map에서 3개만 보여주니까 100% / 3을 했고 map돌릴때 gap을 10px 줘서 -10px을 추가하여 <, > 버튼을 눌렀을때 넓이가 깨지지 않도록한 코드입니다.

2024-01-02 15:39 UTC, lsj0202 commented on apps/client/src/components/qna-posting/QnaPostingCard/index.tsx
> +`;
넵 바꾸겟습니다

2024-01-02 15:40 UTC, lsj0202 commented on apps/client/src/components/qna-posting/QnaPostingList/index.tsx
> +const QnaPostingList = ({ currentQnaPage }) => {
그런가요, 바꾸겟습니다.

2024-01-02 15:42 UTC, SEOKKAMONI commented on apps/client/src/components/qna-posting/QnaPostingCard/index.tsx
> +  flex: 0 0 auto;
flex 0 0 auto 말한거에용!

2024-01-02 16:07 UTC, lsj0202 commented on apps/client/src/components/qna-posting/QnaPostingCard/index.tsx
> +  flex: 0 0 auto;
아하, 그렇군요..  flex: 0 0 auto; 에서 0은 flex-grow이고 자식이 어 그런데 생각해보니까 그냥 flex-shrink: 0 해서 자식요소의 넓이를 그대로 쓰게 하면 해결되는거엿는데 grow, shrink, basis를 다 사용했을까요.. 고쳤습니다!

2024-01-02 16:16 UTC, SEOKKAMONI commented on apps/client/src/components/qna-posting/QnaCategory/index.tsx
> +  width: auto;
https://github.com/price-offer/offer-design-system/blob/b5778edc4edfc078f3eef3e3139ca53248446e63/packages/react/src/components/Badge/index.tsx#L49-L57

width를 쓰지 않고 padding과 height만 준다면 유동적으로 크기가 변하기에 이런 방법을 쓰는것이 더 좋아보여요

2024-01-02 16:19 UTC, SEOKKAMONI commented on apps/client/src/app/career-qna/page.tsx
> +  const handlePrevCareerQna = () => {
```suggestion
  const handlePrevPopularQna = () => {
```

2024-01-02 16:20 UTC, SEOKKAMONI commented on apps/client/src/app/career-qna/page.tsx
> +  const handlePrevCareerQna = () => {
이러한 네이밍이 좀 더 명시적일것같아요 인기 qna를 보여주는거니깐용!

2024-01-02 16:22 UTC, SEOKKAMONI commented on apps/client/src/app/career-qna/page.tsx
> +                  <StyledArrowImage src="/assets/arrow_left.png" />
```suggestion
                  <StyledArrowImage src="/assets/arrow_left.png" />
```

png말고 icon이니깐 [다음](https://github.com/sickgyun/sickgyun-client/blob/main/packages/ui/src/Icons/ArrowBack.tsx)과 같은 svg 컴포넌트로 사용하면 더 유연한 아이콘이 되어 많은 곳에서 사용 할 수 있을것가타용

2024-01-02 16:22 UTC, SEOKKAMONI commented on apps/client/src/app/career-qna/page.tsx
> +                  <StyledArrowImage src="/assets/arrow_right.png" />
마찬가지입니다

2024-01-02 16:22 UTC, SEOKKAMONI commented on apps/client/src/app/career-qna/page.tsx
> +            <QnaPostingList currentQnaPage={currentQnaPage} />
```suggestion
            <QnaPostList currentQnaPage={currentQnaPage} />
```

2024-01-02 16:23 UTC, SEOKKAMONI commented on apps/client/src/app/career-qna/page.tsx
> +            <QnaPostingList currentQnaPage={currentQnaPage} />
currentQnaPage -> currentQnaPageIndex

currentQnaPage는 숫자인게 잘 들어나지 않는 네이밍 같아요

2024-01-02 16:24 UTC, SEOKKAMONI commented on apps/client/src/components/qna-posting/QnaBox/index.tsx
> +  const [activeCategory, setActiveCategory] = useState(0);
```suggestion
  const [activeCategoryIndex, setActiveCategoryIndex] = useState(0);
```

Index를 붙히면 숫자인것이 명시적으로 들어날수있을것같아요

2024-01-02 16:24 UTC, lsj0202 commented on apps/client/src/components/qna-posting/QnaCategory/index.tsx
> +  width: auto;
그렇군요

2024-01-02 16:25 UTC, SEOKKAMONI commented on apps/client/src/components/qna-posting/QnaListBox/index.tsx
> +            <Stack direction="vertical" spacing={0}>
flex 사용해주세요!

2024-01-02 16:26 UTC, SEOKKAMONI commented on apps/client/src/components/qna-posting/QnaListBox/index.tsx
> +                    <Flex alignItems="center" gap="3px">
Flex에는 gap 사용을 하지않습니다 gap을 주려면 Stack을 사용합니다!

2024-01-02 16:27 UTC, SEOKKAMONI commented on apps/client/src/components/qna-posting/QnaListBox/index.tsx
> +                    <Flex alignItems="center" gap="3px">
마찬가지입니다 다 변경부탁드랴요

2024-01-02 16:28 UTC, SEOKKAMONI commented on apps/client/src/components/qna-posting/QnaPostingCard/index.tsx
> +const StyledQnaPostingCard = styled.div`
```suggestion
const StyledQnaPostCard = styled.div`
```

확인좀해주세요...

2024-01-02 23:15 UTC, lsj0202 commented on apps/client/src/app/career-qna/page.tsx
> +  const handlePrevCareerQna = () => {
넵

2024-01-02 23:15 UTC, lsj0202 commented on apps/client/src/app/career-qna/page.tsx
> +                  <StyledArrowImage src="/assets/arrow_left.png" />
넵

2024-01-02 23:20 UTC, lsj0202 commented on apps/client/src/app/career-qna/page.tsx
> +            <QnaPostingList currentQnaPage={currentQnaPage} />
넵! 고쳤습니다

2024-01-02 23:21 UTC, lsj0202 commented on apps/client/src/components/qna-posting/QnaListBox/index.tsx
> +            <Stack direction="vertical" spacing={0}>
넵 바꿨습니다.

2024-01-02 23:21 UTC, lsj0202 commented on apps/client/src/components/qna-posting/QnaListBox/index.tsx
> +                    <Flex alignItems="center" gap="3px">
아하 알겠습니다.

2024-01-02 23:21 UTC, lsj0202 commented on apps/client/src/components/qna-posting/QnaBox/index.tsx
> +  const [activeCategory, setActiveCategory] = useState(0);
그렇군요 알겠습니다.

2024-01-02 23:25 UTC, lsj0202 commented on apps/client/src/components/qna-posting/QnaPostingCard/index.tsx
> +const StyledQnaPostingCard = styled.div`
넵..

2024-01-03 01:04 UTC, lsj0202 commented on apps/client/src/app/career-qna/page.tsx
> +                  <StyledArrowImage src="/assets/arrow_right.png" />
넵

2024-01-03 05:19 UTC, lsj0202 commented on apps/client/src/components/qna-posting/QnaListBox/index.tsx
> +                    <Flex alignItems="center" gap="3px">
넵 알겠습니다.

2024-01-03 14:31 UTC, SEOKKAMONI requested changes
수고하셨습니다

2024-01-03 14:31 UTC, SEOKKAMONI commented on apps/client/src/app/career-qna/page.tsx
> +  const [rightArrowIconColor, setRightArrowIconColor] = useState<string>(colors.gray600);
```suggestion
  const [leftArrowIconColor, setLeftArrowIconColor] = useState(colors.gray600);
  const [rightArrowIconColor, setRightArrowIconColor] = useState(colors.gray600);
```

string으로 추론하기 때문에 불피요한 제네릭 타입이라고 생각되는데 따로 넣으신 이유가 있을까요?

2024-01-03 14:31 UTC, SEOKKAMONI commented on apps/client/src/app/career-qna/page.tsx
> +  };
color를 setState로 변경하는것보다는 동작을 boolean으로 감지하여 color를 삼항으로 핸들링해주는 것이 더 좋아보여요 동작으로 감지하니깐 더 명확하고 지금 처럼 함수 4개가 선언되지않아 복잡도도 줄어드는 효과가 생길 수 있다고 생각해요

### Example
```tsx
const [isActive, setIsActive] = useState(false);

const StyledActiveButton = styled.button<{ isActive: boolean }>`
   color: ${({ isActive }) => isActive ? colors.red : colors.green};
`
```

2024-01-03 14:31 UTC, SEOKKAMONI commented on apps/client/src/components/qna-posting/QnaBox/index.tsx
> +        style={{ height: '90px', borderBottom: '1px solid white' }}
```suggestion
        style={{ height: '90px', borderBottom: `1px solid ${colors.white}` }}
```

혹시 모를 예외 상황을 대비하여 colors를 사용해주세요

2024-01-03 14:31 UTC, SEOKKAMONI commented on apps/client/src/components/qna-posting/QnaBox/index.tsx
> +              <Text fontType="body1">{category.thumbnail}</Text>
text인데 thumbnail이 맞을까요..? 다시 한번만 네이밍 생각해주세요! (제가 전에 리뷰했던 내용 같은데 비즈니스 로직을 몰라서 생긴 문제 같아요 죄송해요)

2024-01-03 14:31 UTC, SEOKKAMONI commented on apps/client/src/components/qna-posting/QnaBox/index.tsx
> +  }
어떤 부분을 담당하나요? 스크린샷 부탁드려요 :)

2024-01-03 14:31 UTC, SEOKKAMONI commented on apps/client/src/components/qna-posting/QnaListBox/index.tsx
> +          onClick={() => setSelectedTitle(qna.id)}
title을 선택하는건데 id가 들어가네요..? 네이밍과 동작이 전혀 맞지 않는것 같아요 다시 한번만 생각해주세요

2024-01-03 14:31 UTC, SEOKKAMONI commented on packages/ui/src/Icons/RightArrow.tsx
> +        fill={color}
```suggestion
        fill="currentColor" 
```

수정해주세요 다른 아이콘들도욥

2024-01-03 23:18 UTC, lsj0202 commented on packages/ui/src/Icons/RightArrow.tsx
> +        fill={color}
넵 수정하겠습니다.

2024-01-03 23:21 UTC, lsj0202 commented on apps/client/src/components/qna-posting/QnaListBox/index.tsx
> +          onClick={() => setSelectedTitle(qna.id)}
그렇군요.. 지금까지 map에서 비교할때는 항상 id로 했었는데 title로 해야 조금더 명시적인것 같습니다.

2024-01-03 23:22 UTC, lsj0202 commented on apps/client/src/components/qna-posting/QnaBox/index.tsx
> +  }
<img width="263" alt="스크린샷 2024-01-04 오전 8 22 41" src="https://github.com/sickgyun/sickgyun-client/assets/102288397/58e61653-de89-4d6c-b922-441ed7285097">

2024-01-03 23:23 UTC, lsj0202 commented on apps/client/src/components/qna-posting/QnaBox/index.tsx
> +  }
파랑색 부분이 ::before 부분에 포함되는 내용입니다.

2024-01-03 23:23 UTC, lsj0202 commented on apps/client/src/components/qna-posting/QnaBox/index.tsx
> +              <Text fontType="body1">{category.thumbnail}</Text>
수정하겠습니다.

2024-01-03 23:25 UTC, lsj0202 commented on apps/client/src/components/qna-posting/QnaBox/index.tsx
> +              <Text fontType="body1">{category.thumbnail}</Text>
<img width="252" alt="스크린샷 2024-01-04 오전 8 25 27" src="https://github.com/sickgyun/sickgyun-client/assets/102288397/549cbaaa-5d5e-4b61-8b99-16210b6fed82">

2024-01-03 23:30 UTC, lsj0202 commented on apps/client/src/components/qna-posting/QnaBox/index.tsx
> +              <Text fontType="body1">{category.thumbnail}</Text>
제가 이모지로 해놔서 혼란을 일으킨거 같습니다.

2024-01-03 23:31 UTC, lsj0202 commented on apps/client/src/components/qna-posting/QnaBox/index.tsx
> +        style={{ height: '90px', borderBottom: '1px solid white' }}
넵

2024-01-03 23:32 UTC, lsj0202 commented on apps/client/src/app/career-qna/page.tsx
> +  const [rightArrowIconColor, setRightArrowIconColor] = useState<string>(colors.gray600);
'"#BBBCC2"' 형식의 인수는 'SetStateAction<"#70737C">' 형식의 매개 변수에 할당될 수 없습니다.
<string>을 써주지 않으면 이렇게 뜨더라구요 그래서 사용했습니다.

2024-01-03 23:36 UTC, lsj0202 commented on apps/client/src/app/career-qna/page.tsx
> +  };
와 이런 방법이 있었네요! 갑사합니다.

2024-01-04 00:55 UTC, SEOKKAMONI commented on apps/client/src/components/qna-posting/QnaBox/index.tsx
> +              <Text fontType="body1">{category.thumbnail}</Text>
네이밍은 emoji가 좋을것같네요!

2024-01-04 00:56 UTC, SEOKKAMONI commented on apps/client/src/components/qna-posting/QnaListBox/index.tsx
> +          onClick={() => setSelectedTitle(qna.id)}
title은 중복이 될 수도 있으니깐 좋은 방법은 아니라고 생각해요 목적이 qna를 선택하는거면 유니크 값인 id가 맞는것같아요 네이밍만 조금 변경하면 좋을것같은데 목적이 들어나도록 `setSelectedQna`가 좋겠네요!

2024-01-04 01:50 UTC, lsj0202 commented on apps/client/src/components/qna-posting/QnaBox/index.tsx
> +              <Text fontType="body1">{category.thumbnail}</Text>
넵

2024-01-04 02:04 UTC, lsj0202 commented on apps/client/src/components/qna-posting/QnaListBox/index.tsx
> +          onClick={() => setSelectedTitle(qna.id)}
그렇군요. 변경하겠습니다.

2024-01-05 00:52 UTC, SEOKKAMONI approved these changes
수고하셨습니다~~!!

2024-01-05 00:52 UTC, SEOKKAMONI commented on apps/client/src/app/page.tsx
> +    router.push('/career-qna');
그냥 qna로 해야 확장성있을것같아요

2024-01-05 00:58 UTC, lsj0202 commented on apps/client/src/app/career-qna/page.tsx
> +                  firstOrLastPage={isFirstPage}
isFirst이거나 isLast가 참이라면 falstOrLastPage에 들어가서 버튼에 색이 바뀌도록 하였습니다.

2024-01-05 00:58 UTC, lsj0202 commented on apps/client/src/app/page.tsx
> +    router.push('/career-qna');
넵

2024-01-05 01:24 UTC, SEOKKAMONI commented on apps/client/src/app/qna/page.tsx
> +                  isFirstOrLastPage={isLastPage}
그냥 isFirstPage랑 isLastPage랑 나누는게 더 좋을것같아요 하나의 변수명에 두개의 의미를 담는것은 별로 좋지 않아보여요

2024-01-05 01:25 UTC, lsj0202 commented on apps/client/src/app/qna/page.tsx
> +                  isFirstOrLastPage={isLastPage}
넵

2024-01-05 01:36 UTC, SEOKKAMONI requested changes

2024-01-05 01:36 UTC, SEOKKAMONI commented on apps/client/src/app/qna/page.tsx
> +                  isLastPage={false}
이거 넣지 않아도 되는 방법이 있어요

2024-01-05 01:36 UTC, SEOKKAMONI commented on apps/client/src/app/qna/page.tsx
> +const StyledActiveButton = styled.button<{ isFirstPage: boolean; isLastPage: boolean }>`
<{ isFirstPage?: boolean; isLastPage?: boolean }>

ㄱㄱ

2024-01-05 01:52 UTC, SEOKKAMONI approved these changes
지금 메인에 있는거 가지고와서 제가 한 작업물이랑 같이 보이는 현상있는데 다음부터는 가지고오지말아주세요 파일체인지가 너무 많아져서 리뷰하기 힘들어요!

2024-01-05 01:53 UTC, merged