feat(client): qna 바로가기 bar 생성
sickgyun/sickgyun-client pull request #140
Opened 2024-01-06 12:34 UTC by lsj0202

## ⛳️작업 내용

- qna 바로가기 개발

## 📸스크린샷

## 📎레퍼런스

2024-01-07 09:08 UTC, SEOKKAMONI reviewed
디자인 좀 어떻게 해봐...

2024-01-07 09:08 UTC, SEOKKAMONI commented on apps/client/src/app/page.tsx
> +    router.push(`/qna?position=${queryParams}`);
position이 적절한 query 네이밍인가여..? category가 적절하지않을까요?

2024-01-07 23:20 UTC, lsj0202 commented on apps/client/src/app/page.tsx
> +    router.push(`/qna?position=${queryParams}`);
그렇네요

2024-01-08 13:45 UTC, SEOKKAMONI requested changes
P1) 디자인 좀 어떻게 해봐요 다른 사이트 참고좀!!

2024-01-27 06:19 UTC, SEOKKAMONI approved these changes
Lgtm

2024-01-27 06:19 UTC, merged